/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.keepersecurity.secretsManager.core

fun doSomethingElse(): Boolean {
    return true
}

class SecretsManager {
    fun doSomething(): Boolean {
        return true
    }
}
