---
version: 3
images:
  base_image:
    name: docker.io/redhat/ubi9:latest

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend_final:
    - RUN $PKGMGR install -y openssh-clients sshpass rsync git krb5-workstation && $PKGMGR clean all