name: Publish package to the Maven Central Repository
on:
#  release:
#    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: prod

    defaults:
      run:
        working-directory: ./sdk/java/core

    steps:

      - name: Retrieve secrets from KSM
        id: ksmsecrets
        uses: Keeper-Security/ksm-action@master
        with:
          hostname: keepersecurity.eu
          keeper-secret-config: ${{ secrets.KSM_ARTIFACT_JAVA_APP_CONFIG }}
          secrets: |
            zOVOneDczofWFlfizjC5Qw file:90A46CD1-private-key.asc | file:/tmp/signing_secret_key_ring_file.asc
            zOVOneDczofWFlfizjC5Qw custom:signing.keyId | out:signing_key_id
            zOVOneDczofWFlfizjC5Qw custom:signing.password | out:signing_password
            zOVOneDczofWFlfizjC5Qw custom:ossrhUsername | out:ossrh_username
            zOVOneDczofWFlfizjC5Qw custom:ossrhPassword | out:ossrh_password

      - uses: actions/checkout@v2
      
      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Publish package
        env:
          SIGNING_SECRET_KEY_RING_FILE: /tmp/signing_secret_key_ring_file.asc
          SIGNING_KEY_ID: ${{ fromJSON(steps.ksmsecrets.outputs.out-secrets).signing_key_id }}
          SIGNING_PASSWORD: ${{ fromJSON(steps.ksmsecrets.outputs.out-secrets).signing_password }}
          OSSRH_USERNAME: ${{ fromJSON(steps.ksmsecrets.outputs.out-secrets).ossrh_username }}
          OSSRH_PASSWORD: ${{ fromJSON(steps.ksmsecrets.outputs.out-secrets).ossrh_password }}

        run: gradle publishMavenJavaPublicationToSonatypeRepository
