name: Test-JS

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/javascript/packages/core/**'
      - '.github/workflows/test.js.yml'

permissions:
  contents: read

jobs:
  test-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '20', '22', '24' ]
    name: KSM test with Node.js ${{ matrix.node-version }}
    defaults:
      run:
        working-directory: ./sdk/javascript/packages/core
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        env:
          NPM_TOKEN: ""
      - run: npm test
        env:
          NPM_TOKEN: ""
