name: Test-Java

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/java/core/**'
      - '.github/workflows/test.java.yml'

permissions:
  contents: read

jobs:
  test-java:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        java-version: [ '8', '11', '17', '21' ]
    name: KSM test with Java ${{ matrix.java-version }}
    defaults:
      run:
        working-directory: ./sdk/java/core
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java-version }}

    - name: Setup, Build and Test
      uses: gradle/actions/setup-gradle@0b6dd653ba04f4f93bf581ec31e66cbd7dcb644d # v4
      with:
        gradle-version: '8.14'
        arguments: build test
        build-root-directory: ./sdk/java/core
