name: Test-ServiceNow

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'integration/servicenow-external-credential-resolver/**'
      - '.github/workflows/test.servicenow.yml'

jobs:
  test-servicenow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - mid-release: utah
            java-version: '11'
          - mid-release: zurich
            java-version: '17'
    name: KSM ServiceNow test with Java ${{ matrix.java-version }} (${{ matrix.mid-release }})
    defaults:
      run:
        working-directory: ./integration/servicenow-external-credential-resolver
    steps:
      - uses: actions/checkout@v5
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Build and test
        run: |
          chmod u+x gradlew
          ./gradlew test -PmidRelease="${{ matrix.mid-release }}" --no-daemon
