name: Test-Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-go:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./sdk/golang/src/keepersecurity.com/test/
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -p 1 ./...
