name: Test JavaScript Storage - GCP KMS

on:
  push:
    branches:
      - 'release/storage/javascript/gcp-kms/**'
    paths:
      - 'sdk/javascript/packages/gcp/**'
      - '.github/workflows/test.javascript.storage.gcp.kms.yml'
  pull_request:
    branches:
      - master
      - 'release/storage/javascript/gcp-kms/**'
    paths:
      - 'sdk/javascript/packages/gcp/**'
      - '.github/workflows/test.javascript.storage.gcp.kms.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/javascript/packages/gcp
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js 22.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22.x'
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
