name: Test-Java

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/java/core/**'
      - '.github/workflows/test.java.yml'

permissions:
  contents: read

jobs:
  test-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '8', '11', '17', '21' ]
    name: KSM test with Java ${{ matrix.java-version }}
    defaults:
      run:
        working-directory: ./sdk/java/core
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      with:
        gradle-version: '8.14'

    - name: Build and Test
      run: gradle build test
