name: Test Python Storage - GCP KMS

on:
  push:
    branches:
      - 'release/storage/python/gcp-kms/**'
    paths:
      - 'sdk/python/storage/keeper_secrets_manager_storage_gcp_kms/**'
      - 'sdk/python/core/**'
      - '.github/workflows/test.python.storage.gcp.kms.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'sdk/python/storage/keeper_secrets_manager_storage_gcp_kms/**'
      - 'sdk/python/core/**'
      - '.github/workflows/test.python.storage.gcp.kms.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        working-directory: ./sdk/python/storage/keeper_secrets_manager_storage_gcp_kms
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt pytest pytest-cov
          uv pip install -e .
      - name: Run tests
        run: pytest tests/
